/**
 * cdocs-hooks.ts — OpenCode plugin for CDocs frontmatter validation.
 *
 * This is the OC equivalent of the CC PostToolUse hook
 * (cdocs-validate-frontmatter.sh). It validates frontmatter fields
 * on cdocs files after Write/Edit operations.
 *
 * NOT ported from CC:
 * - inject-rules.sh: OC reads .claude/rules/ natively; no injection needed.
 * - validate-cdocs-edit-path.sh: OC events lack agent identity, so
 *   agent-scoped path restriction cannot be implemented without blocking
 *   the main session. See proposal edge case "Cross-target parity gap".
 *
 * DO NOT manually edit this file in opencode/plugins/.
 * This file is hand-written (not generated by the build script),
 * but it lives in the generated output directory for npm packaging.
 *
 * @see plugins/cdocs/hooks/cdocs-validate-frontmatter.sh (CC equivalent)
 */

import type { Plugin } from "opencode";
import { readFileSync } from "fs";
import { basename } from "path";

/** Required frontmatter fields for all cdocs documents. */
const REQUIRED_FIELDS = ["first_authored", "type", "state", "status"];

/** Pattern matching cdocs document directories. */
const CDOCS_PATH_RE = /cdocs\/(devlogs|proposals|reviews|reports)\//;

/**
 * Extract the file path from an OC tool event.
 * OC Write/Edit events include the file path in the tool input.
 */
function extractFilePath(event: { input?: Record<string, unknown> }): string | undefined {
  const filePath = event.input?.file_path;
  if (typeof filePath === "string" && filePath.length > 0) {
    return filePath;
  }
  return undefined;
}

/**
 * Check if a file has the required cdocs frontmatter fields.
 * Uses regex-based detection (no YAML parser), matching the CC hook approach.
 *
 * Returns an array of missing field names, or empty if all present.
 */
function validateFrontmatter(filePath: string): string[] {
  let content: string;
  try {
    content = readFileSync(filePath, "utf-8");
  } catch {
    // File does not exist or is unreadable — skip silently
    return [];
  }

  // Take first 50 lines for frontmatter inspection
  const head = content.split("\n").slice(0, 50).join("\n");

  // Check for frontmatter delimiters
  if (!head.includes("---")) {
    return ["(no frontmatter found)"];
  }

  const missing: string[] = [];
  for (const field of REQUIRED_FIELDS) {
    const fieldRe = new RegExp(`^${field}:`, "m");
    if (!fieldRe.test(head)) {
      missing.push(field);
    }
  }

  return missing;
}

export default {
  name: "cdocs-hooks",
  version: "0.1.0",

  setup(plugin: Plugin) {
    // Frontmatter validation on Write/Edit to cdocs paths
    // Equivalent to CC PostToolUse cdocs-validate-frontmatter.sh
    plugin.on("tool.execute.after", async (event) => {
      const filePath = extractFilePath(event);
      if (!filePath) return;

      // Only validate cdocs markdown files
      if (!CDOCS_PATH_RE.test(filePath)) return;

      // Skip README files
      if (basename(filePath) === "README.md") return;

      const missing = validateFrontmatter(filePath);

      if (missing.length === 0) return;

      if (missing.includes("(no frontmatter found)")) {
        return {
          additionalContext: `CDocs: File ${filePath} is missing YAML frontmatter. All cdocs documents require frontmatter with: ${REQUIRED_FIELDS.join(", ")} fields.`,
        };
      }

      return {
        additionalContext: `CDocs: File ${filePath} is missing required frontmatter fields: ${missing.join(" ")}. See frontmatter spec for requirements.`,
      };
    });
  },
} satisfies Plugin;
