/**
 * cdocs-hooks.ts — OpenCode plugin for CDocs frontmatter validation.
 *
 * This is the OC equivalent of the CC PostToolUse hook
 * (cdocs-validate-frontmatter.sh). It validates frontmatter fields
 * on cdocs files after Write/Edit operations.
 *
 * NOT ported from CC:
 * - inject-rules.sh: OC reads .claude/rules/ natively; no injection needed.
 * - validate-cdocs-edit-path.sh: OC events lack agent identity, so
 *   agent-scoped path restriction cannot be implemented without blocking
 *   the main session. See proposal edge case "Cross-target parity gap".
 *
 * This file is hand-written (not generated by the build script).
 * Canonical location: plugins/cdocs/hooks/cdocs-hooks.ts
 * Build copies it to: build/cdocs/opencode/plugins/cdocs-hooks.ts
 *
 * @see plugins/cdocs/hooks/cdocs-validate-frontmatter.sh (CC equivalent)
 */

import type { Plugin } from "@opencode-ai/plugin";
import { readFileSync } from "fs";
import { basename } from "path";

/** Required frontmatter fields for all cdocs documents. */
const REQUIRED_FIELDS = ["first_authored", "type", "state", "status"];

/** Pattern matching cdocs document directories. */
const CDOCS_PATH_RE = /cdocs\/(devlogs|proposals|reviews|reports)\//;

/**
 * Extract the file path from an OC tool event input.
 * OC Write/Edit events include the file path in the args.
 */
function extractFilePath(input: Record<string, unknown>): string | undefined {
  // OC tool.execute.after receives input with the tool's arguments
  // The file path field varies by tool: filePath for Write, filePath for Edit
  const filePath = input.filePath || input.file_path;
  if (typeof filePath === "string" && filePath.length > 0) {
    return filePath;
  }
  return undefined;
}

/**
 * Check if a file has the required cdocs frontmatter fields.
 * Uses regex-based detection (no YAML parser), matching the CC hook approach.
 *
 * Returns an array of missing field names, or empty if all present.
 */
function validateFrontmatter(filePath: string): string[] {
  let content: string;
  try {
    content = readFileSync(filePath, "utf-8");
  } catch {
    // File does not exist or is unreadable: skip silently
    return [];
  }

  // Take first 50 lines for frontmatter inspection
  const head = content.split("\n").slice(0, 50).join("\n");

  // Check for frontmatter delimiters
  if (!head.includes("---")) {
    return ["(no frontmatter found)"];
  }

  const missing: string[] = [];
  for (const field of REQUIRED_FIELDS) {
    const fieldRe = new RegExp(`^${field}:`, "m");
    if (!fieldRe.test(head)) {
      missing.push(field);
    }
  }

  return missing;
}

/**
 * CDocs frontmatter validation plugin for OpenCode.
 * Hooks into tool.execute.after to validate cdocs files after Write/Edit.
 */
const cdocsHooks: Plugin = async (_ctx) => {
  return {
    "tool.execute.after": async (input, _output) => {
      const filePath = extractFilePath(input as Record<string, unknown>);
      if (!filePath) return;

      // Only validate cdocs markdown files
      if (!CDOCS_PATH_RE.test(filePath)) return;

      // Skip README files
      if (basename(filePath) === "README.md") return;

      const missing = validateFrontmatter(filePath);

      if (missing.length === 0) return;

      if (missing.includes("(no frontmatter found)")) {
        console.warn(
          `CDocs: File ${filePath} is missing YAML frontmatter. All cdocs documents require frontmatter with: ${REQUIRED_FIELDS.join(", ")} fields.`
        );
        return;
      }

      console.warn(
        `CDocs: File ${filePath} is missing required frontmatter fields: ${missing.join(" ")}. See frontmatter spec for requirements.`
      );
    },
  };
};

export default cdocsHooks;
